name: 'Terraform plan preview'

on:  
  pull_request:
    branches:
      - master

jobs:
  include:
    uses: ./.github/workflows/terraform.yml
    with:
      apply: false
      account: preview
    secrets:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
