name: "Terraform"

on:
  workflow_call:
    inputs:
      apply:
        required: true
        type: boolean
      account:
        required: true
        type: string
    secrets:
      AWS_ACCOUNT_ID:
        required: true

permissions:
  id-token: write
  pull-requests: write
  contents: read
  packages: read

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v2

      # Install the latest version of Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.3
          terraform_wrapper: false

      # Install Terragrunt
      - name: Setup Terragrunt
        uses: autero1/action-terragrunt@v1.1.1
        with:
          terragrunt_version: 0.35.20



      # Get AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/nw-role-github-actions
          aws-region: eu-central-1

      # Checks that all Terraform configuration files adhere to a canonical format
      - name: Terraform Format
        run: terraform fmt -check